#!/bin/sh

if [[ -d "app/" ]]; then
	echo "Set permissions for Magento project in $PWD"
else
	echo "Current directory doesn't appear to be a Magento root"
	exit 1
fi

find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;

chown -R :psacln ./*

chmod o+w var var/.htaccess includes includes/config.php app/etc
chmod -R o+w media
chmod 550 mage;
#chmod 550 pear;
