#!/usr/bin/env bash

main() {
    if [[ -d "app/" ]]; then
        echo "Set permissions for Magento project in $PWD"
    else
        echo "Current directory doesn't appear to be a Magento root"
        exit 1
    fi

    local verbose="";
    if [[ $* == *-v* ]]; then
        verbose="-v";
    fi

    find . -type f -exec chmod ${verbose} 644 "{}" \;
    find . -type d -exec chmod ${verbose} 755 "{}" \;

    if [[ "$#" -gt "0" ]]; then
        local group="$1";
        echo "Set file group: $group";
        chown -R ${verbose} :${group} ./*
    fi

    chmod o+w var var/.htaccess includes includes/config.php app/etc
    chmod -R o+w media
    chmod 550 mage;
}

main "$@";
