#!/usr/bin/env bash
set -o nounset
set -e

if hash realpath 2> /dev/null; then
    DIR="$( cd "$(dirname $(realpath "${BASH_SOURCE[0]}" ))" && pwd )";
elif hash readlink 2> /dev/null && [[ "$(uname -s)" != "Darwin" ]]; then
    DIR="$( cd "$(dirname $(readlink -f "${BASH_SOURCE[0]}" ))" && pwd )";
else
    DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )";
fi

if [[ -e "lib.sh" ]]; then source "lib.sh"; fi
source "$DIR/lib.sh";

function mage::watch::help() {
    echo "Usage: $0 command

system      Watch the system log
exception   Watch the exception log
debug       Watch the debug log

";
}

function _check_log_dir() {
    lib::go_to_magento_root;

	if [[ ! -d "var/log/" ]]; then
		lib::print_error "The log directory var/log/ doesn't seem to exist";
		exit 1;
	fi
}

function _check_log_file() {
	if [[ ! -e "var/log/$1.log" ]]; then
		lib::print_error "The log file var/log/$1.log doesn't seem to exist";
		exit 1;
	fi
}

function _watch() {
    local file_name="$1";
    shift;
    _check_log_dir;
    _check_log_file "$file_name";
    tail -fn 45 --sleep-interval=5 "var/log/$file_name.log" "$@";
}

function mage::watch::system () {
    _watch "system" "$@";
}

function mage::watch::exception() {
    _watch "exception" "$@";
}

function mage::watch::debug() {
    _watch "debug" "$@";
}

function mage::watch::sys() {
   mage::watch::system "$@";
}

function mage::watch::exc() {
    mage::watch::exception "$@";
}

lib::sub_command::run "mage::watch" "$@";
