#!/usr/bin/env bash
set -o nounset
set -e

if hash realpath 2> /dev/null; then
    DIR="$( cd "$(dirname $(realpath "${BASH_SOURCE[0]}" ))" && pwd )";
elif hash readlink 2> /dev/null && [[ "$(uname -s)" != "Darwin" ]]; then
    DIR="$( cd "$(dirname $(readlink -f "${BASH_SOURCE[0]}" ))" && pwd )";
else
    DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )";
fi

if [[ -e "lib.sh" ]]; then source "lib.sh"; fi
source "$DIR/lib.sh";

function mage::info::help() {
    echo "Usage: $0 command

version     Print the installed Magento version

";
}

function mage::info::version () {
    lib::get_magento_version;
}

lib::sub_command::run "mage::info" "$@";
