#!/usr/bin/env bash
set -o nounset
set -e

if hash realpath 2> /dev/null; then
    DIR="$( cd "$(dirname $(realpath "${BASH_SOURCE[0]}" ))" && pwd )";
elif hash readlink 2> /dev/null && [[ "$(uname -s)" != "Darwin" ]]; then
    DIR="$( cd "$(dirname $(readlink -f "${BASH_SOURCE[0]}" ))" && pwd )";
else
    DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )";
fi

source "$DIR/lib.sh";

function print_usage() {
    echo "Usage: $0 command

system      Watch the system log
exception   Watch the exception log
debug       Watch the debug log

";
}

function _check_log_dir() {
    lib::check_magento_root;

	if [[ ! -d "var/log/" ]]; then
		lib::print_error "The log directory var/log/ doesn't seem to exist";
		exit 1;
	fi
}

function _check_log_file() {
	if [[ ! -e "var/log/$1.log" ]]; then
		lib::print_error "The log file var/log/$1.log doesn't seem to exist";
		exit 1;
	fi
}

function _watch() {
    _check_log_dir;
    _check_log_file "$1";
    tail -fn 45 --sleep-interval=5 "var/log/$1.log";
}

function mage::system () {
    _watch "system";
}

function mage::exception() {
    _watch "exception";
}

function mage::debug() {
    _watch "debug";
}

function mage::sys() {
    mage::system;
}

function mage::exc() {
    mage::exception;
}

function run () {
    if [[ "$#" -lt "1" ]]; then
        lib::print_error "Missing argument 'command'";
        print_usage;

        exit 1;
    fi

    lib::check_utilities;

    COMMAND="$1";
    shift;

    if type "mage::$COMMAND" &> /dev/null; then
        mage::${COMMAND} "$@";
    else
        lib::print_error "Command '$COMMAND' not found";
    fi
}

run "$@";
