#!/bin/bash
if [[ -d "app/" ]]; then
	if [[ -d "var/log/" ]]; then
		tail -fn 45 --sleep-interval=5 var/log/exception.log
	else
		echo "The log directory var/log/ doesn't seem to exist"
	fi
else
	echo "Your not in a Magento root"
fi
