#!/usr/bin/env bash
set -o nounset
set -e

if hash realpath 2> /dev/null; then
    DIR="$( cd "$(dirname $(realpath "${BASH_SOURCE[0]}" ))" && pwd )";
elif hash readlink 2> /dev/null && [[ "$(uname -s)" != "Darwin" ]]; then
    DIR="$( cd "$(dirname $(readlink -f "${BASH_SOURCE[0]}" ))" && pwd )";
else
    DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )";
fi

: ${VERBOSE=""}

if [ -e "lib.sh" ]; then source "lib.sh"; fi
source "$DIR/lib.sh";


function load_scripts() {
    for file in ${DIR}/scripts/*.sh; do
        source "$file";
    done
}
function list_scripts() {
     typeset -f | awk '/ \(\) $/ && !/^main / {print $1}' | grep 'mage::'
}

function mage::selfupdate() {
    lib::selfupdate;
}

function mage::help() {
    echo "Usage: $0 command-set command

selfupdate  Update the mage_tools
info        Print information about the Magento system
patch       Patch related tasks
watch       Watch log files
report      Print error reports

";

    list_scripts | while read line; do
        echo "$line" | sed -e 's/mage:://g'
#        ${line};
    done
}

function run () {
    if [[ "$#" -lt "1" ]]; then
        lib::print_error "Missing argument 'command-set'";
        mage::help;

        exit 1;
    fi

    lib::check_utilities;
    load_scripts;

    COMMAND_SET="$1";
    shift;



    if [ "$COMMAND_SET" == "--help" ] || [ "$COMMAND_SET" == "help" ]; then
        mage::help;
    elif type "mage::$COMMAND_SET" &> /dev/null; then
        mage::${COMMAND_SET} "$@";
    elif type "mage::$COMMAND_SET" &> /dev/null; then
        mage::${COMMAND_SET} "$@";
    elif [[ -e "$(lib::get_script_directory)/mage_$COMMAND_SET" ]]; then
        /usr/bin/env bash "$(lib::get_script_directory)/mage_$COMMAND_SET" "$@";
    elif [[ -e "$(lib::get_script_directory)/mage_$COMMAND_SET.sh" ]]; then
        /usr/bin/env bash "$(lib::get_script_directory)/mage_$COMMAND_SET.sh" "$@";
    else
        lib::print_error "Command-set '$COMMAND_SET' not found";
    fi
}

run "$@";
