#!/usr/bin/env bash

_mage::_list_commands() {
    local help="";
    if [ "$#" -gt "0" ]; then
        help="$(../mat $1 --help 2> /dev/null)";
    else
        help="$(../mat help 2> /dev/null)";
    fi
    echo "$help" | tail -n +3 | awk '{ print $1 }';
}

_mat() {
    COMPREPLY=()
    local opts;
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ "${prev}" != "" ] && [ "${prev}" != "mat" ]; then
        opts="$(_mage::_list_commands ${prev})";
    else
        opts="$(_mage::_list_commands)";
    fi

    local matches=$(compgen -W "${opts}" -- ${cur});
    if [ "$matches" != "" ];then
        COMPREPLY=( ${matches} )
    else
        COMPREPLY=( $(compgen -f ${cur}) )
    fi
}

complete -F _mat mat
